### ISSUE TITLE
Error: ENOENT: no such file or directory, stat build/index.html

### ISSUE THREAD

**Issue by nawaabazmi** [jamalag/webrtc#2]
i was following your video and saw build folder over there but here when i ran node server.js 
it give mentioned error then checked the folder there was no build folder

please do explain about that build folder and what's that in your index.html

**Comment by jamalag** [comment]
Hi nawaabazmi,
After cloning the repo, you need to do the following before you run the server ...
1. npm install (to download nodemodules)
2. npm run build (to create build folder and generate client files - including index.html)
3. node server.js (to run the server)

But because webRTC will not work without https, quick solution is to use ngrok tunnel.

good luck.
